# Generated by Django 4.1.5 on 2023-01-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continent',
            old_name='country_name',
            new_name='continent_name',
        ),
    ]
